### ISSUE TITLE
About encode range

### ISSUE THREAD

**Issue by HiroakiSuziki** [nayuki/Reference-arithmetic-coding#14]
Can this implementation be used to encode 16bit images?

**Comment by nayuki** [comment]
The answer to your question depends on many factors.

First you need to set `ArithmeticCoderBase.numStateBits`. In Java this value can be in the range [1, 62], and 32 is recommended. In Python this value needs to be at least 1 and has no upper limit.

If you want to encode 16-bit symbols, then you need numStateBits >= 16. More state bits will give you more range for the frequency table.

However, there are other approaches too. I heard that H.264/AVC uses binary arithmetic coding, and I think they convert 16-bit values into a sequence of sixteen 1-bit values and send each bit individually through the CABAC.
