### ISSUE TITLE
Proposal: to use std::Map for FrequencyTable

### ISSUE THREAD

**Issue by fshabashev** [nayuki/Reference-arithmetic-coding#17]
Hi @nayuki
I like your implementation of the arithmetic encoding and I think I can make it work with any UTF-8 characters if we add a Binary tree-based FrequencyTable implementation. 

If you are accepting pull requests I can add the implementation.

**Comment by nayuki** [comment]
Thanks for the ideas, but I prefer to work with bytes and not Unicode characters, as UTF-8 decoding comes with a lot of gotchas like out of range, overlong, invalid bytes, and many other issues.
