### ISSUE TITLE
parallel arithmetic coding

### ISSUE THREAD

**Issue by yuanenming** [nayuki/Reference-arithmetic-coding#19]
Thanks for sharing your implementation, it's really well-organized and easy to follow.
I am trying to use arithmetic coding for neural network-based text compression. It is very time-consuming when encoding large text corpus because it is essentially sequential. I did not find a parallel open-source implementation. So I am wondering if it is easy to be parallel. Could you please give me some hints?

**Comment by yuanenming** [comment]
encoding I mean, I know that decoding is hard to parallel.

**Comment by nayuki** [comment]
No free help or explanation is provided for new features. https://www.nayuki.io/page/about#contact
