### ISSUE TITLE
Can we add the LICENSE to the repository?

### ISSUE THREAD

**Issue by Smerity** [nayuki/Reference-arithmetic-coding#3]
Hi @nayuki - thanks so much for the clean implementations, it's brilliant! :)

I noticed you've listed [the licenses for your projects](https://www.nayuki.io/page/overview-of-project-nayuki-software-licenses) (thanks for making so many of the OSS!) and that this repository is listed under the MIT License.

Can the MIT License be added as a LICENSE to the repository? If so, I'm happy for you to reply with a Yes and I can do the work on adding and sending a pull request to minimize the work for you ^_^

As background, I'm interested in modifying this for research code but as I'm at a commercial research lab (though we publish openly, both papers and [code](https://github.com/salesforce/awd-lstm-lm)! ^_^) I wanted to make sure there's no disagreement between this index page and a project’s main page (and I think having the LICENSE in the repo would make legal happier) :)

**Comment by nayuki** [comment]
Thanks for the offer, but I would decline the change. The readme file is short enough that I see it unnecessary to add a separate license file. I believe the license text is fine as it stands. Hope you're getting some good usage out of my reference arithmetic coding implementation!

**Comment by Smerity** [comment]
Oh gosh, I somehow missed you'd noted the license when reading the readme, my apologies!

At least this provided me the chance to thank you for your various explanatory codebases in person ^_^

**Comment by nayuki** [comment]
Yes, I look forward to seeing your upcoming work (such as the Salesforce repo you linked). Thanks again for dropping a line!
