### ISSUE TITLE
Error finishing encoder stream

### ISSUE THREAD

**Issue by borneq** [nayuki/Reference-arithmetic-coding#9]
(c++)I am using Encode in own stream and if I write 3 symbol, no byte is outputted.
```cpp
void ArithmeticEncoder::finish() {
	output.write(1);
}
```
must also call BitOutputStream::finish() 
in my test program:
```cpp
#include <iostream>
#include <fstream>
#include "ArithmeticEncoder.h" //I changed *.hpp to my own files, but It is small change
#include "ArithmeticDecoder.h"
#include "SimpleFrequencyTable.h"

int main()
{
	std::filebuf fb;
	fb.open("test.txt", std::ios::out);
	std::ostream os(&fb);
	std::vector<uint32_t> freqvec;
	freqvec.push_back(10);
	freqvec.push_back(20);
	freqvec.push_back(30);
	SimpleFrequencyTable freqs(freqvec);
	BitOutputStream out(os);
	{
		ArithmeticEncoder encoder(9, out);
		encoder.write(freqs, 0);
		encoder.write(freqs, 1);
		encoder.write(freqs, 2);	
		encoder.finish();
	}
	fb.close();
	std::filebuf fb1;
	fb1.open("test.txt", std::ios::in);
	std::istream in(&fb1);
	BitInputStream inp(in);
	ArithmeticDecoder decoder(9, inp);
	for (int i=0; i<4; i++) //4 because I test symbol out of stream
	{
		uint32_t symbol = decoder.read(freqs);
		printf("symbol=%d\n", symbol);
	}
}
```

**Comment by nayuki** [comment]
* You need to open the arithmetic-coded file in binary mode, not text mode. See https://github.com/nayuki/Reference-arithmetic-coding/blob/deb456ffc08f44fc1973c7836198222861bc2f87/cpp/AdaptiveArithmeticCompress.cpp#L40

* You need to call `BitOutputStream.finish()`, see https://github.com/nayuki/Reference-arithmetic-coding/blob/deb456ffc08f44fc1973c7836198222861bc2f87/cpp/AdaptiveArithmeticCompress.cpp#L59

* There might exist other issues in your code. Please follow my example code faithfully before reporting a problem.
